[package]
name = "rpc"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
test-support = []

[dependencies]
crypto = { path = "../crypto/" }
logging = { path = "../logging" }
subsystem = { path = "../subsystem" }
utils = { path = "../utils/" }
utils-networking = { path = "../utils/networking" }

anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
http.workspace = true
hyper.workspace = true
jsonrpsee = { workspace = true, features = ["server", "server-core", "http-client", "ws-client", "macros"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tower = { workspace = true, features = ["util"] }
tower-http = { workspace = true, features = ["auth", "set-header"] }

[dev-dependencies]
test-utils = { path = "../test-utils" }

rstest.workspace = true
tokio.workspace = true
