[package]
name = "wallet"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
consensus = { path = "../consensus" }
crypto = { path = "../crypto/" }
logging = { path = "../logging" }
pos_accounting = { path = "../pos_accounting" }
serialization = { path = "../serialization" }
mempool = { path = "../mempool" }
storage = { path = "../storage", features = ["inmemory"] }
tx-verifier = { path = "../chainstate/tx-verifier" }
chainstate = { path = "../chainstate" }
utils = { path = "../utils" }
utxo = { path = "../utxo" }
wallet-storage = { path = "./storage" }
wallet-types = { path = "./types" }

bip39 = { workspace = true, default-features = false, features = ["std", "zeroize"] }
hex.workspace = true
itertools.workspace = true
parity-scale-codec.workspace = true
serde.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
test-utils = { path = "../test-utils" }

rstest.workspace = true
tempfile.workspace = true
