[package]
name = "gen-rpc-docs"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]

blockprod = { path = "../../blockprod" }
chainstate = { path = "../../chainstate" }
mempool = { path = "../../mempool" }
node-lib = { path = "../../node-lib" }
p2p = { path = "../../p2p" }
rpc-description = { path = "../description" }
test-rpc-functions = { path = "../../test-rpc-functions" }
wallet-rpc-lib = { path = "../../wallet/wallet-rpc-lib" }

clap.workspace = true
