version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: use-strong-password

  api-web-server:
    image: mintlayer/api-web-server:0.3.0
    volumes:
      - mintlayer_data:/home/mintlayer/
    command: api-web-server --rpc-address node-daemon:3030 --postgres-host postgres --postgres-password use-strong-password --postgres-database mintlayer_chain
    depends_on:
      - node-daemon
    ports:
      - "3000:3000"

  node-daemon:
    image: mintlayer/node-daemon:0.3.0
    volumes:
      - mintlayer_data:/home/mintlayer/
    command: node-daemon mainnet --http-rpc-addr 0.0.0.0:3030
    ports:
      - "3030:3030"


volumes:
  mintlayer_data:
