[package]
name = "wallet-rpc-client"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
chainstate = { path = "../../chainstate" }
logging = { path = "../../logging" }
node-lib = { path = "../../node-lib" }
rpc = { path = "../../rpc" }
serialization = { path = "../../serialization" }
subsystem = { path = "../../subsystem" }
wallet-rpc-lib = { path = "../wallet-rpc-lib" }
wallet-types = { path = "../types" }
wallet-controller = { path = "../wallet-controller" }
node-comm = { path = "../wallet-node-client" }
p2p-types = { path = "../../p2p/types" }

async-trait.workspace = true
base64.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tower.workspace = true

jsonrpsee = { workspace = true, default-features = false }

[dev-dependencies]
chainstate-storage = { path = "../../chainstate/storage" }

tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }
