services:
  node:
    build:
      context: ../..
      dockerfile: build-tools/p2p-test/Dockerfile
    command: bash -c "
        node-daemon testnet \
            --rpc-bind-address 0.0.0.0:$RPC_PORT \
            $(dig +short $NODES_LIST | xargs printf '--p2p-boot-node %s ') \
            --p2p-force-dns-query-if-no-global-addresses-known \
      "
    environment:
      - RUST_LOG
