[package]
name = "utils"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
crypto = { path = "../crypto/" }
logging = {path = '../logging'}
serialization = { path = "../serialization" }

clap = { workspace = true, features = ["env", "string"] }
directories.workspace = true
heck.workspace = true
num-traits.workspace = true
parity-scale-codec.workspace = true
probabilistic-collections.workspace = true
qrcodegen.workspace = true
slave-pool.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
test-utils = { path = "../test-utils" }

criterion.workspace = true
rstest.workspace = true
static_assertions.workspace = true

[target.'cfg(loom)'.dependencies]
loom.workspace = true

[[bench]]
name = "benches"
harness = false
