[package]
name = "api-blockchain-scanner-lib"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api-server-common = { path = "../api-server-common" }
chainstate = { path = "../../chainstate" }
common = { path = "../../common" }
logging = { path = "../../logging" }
node-comm = { path = "../../wallet/wallet-node-client" }
pos-accounting = { path = "../../pos-accounting" }
utils = { path = "../../utils" }
tx-verifier = { path = "../../chainstate/tx-verifier" }
constraints-value-accumulator = { path = "../../chainstate/constraints-value-accumulator" }
mempool = { path = "../../mempool" }

async-trait.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
chainstate-test-framework = { path = "../../chainstate/test-framework" }
crypto = { path = "../../crypto" }
test-utils = { path = "../../test-utils" }
serialization = { path = "../../serialization" }

rstest.workspace = true
