name: Wasm build and test

on:
  push:
    branches:
      - "**" # target all branches
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug
  RUST_BACKTRACE: full

jobs:
  wasm_with_nodejs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Update local dependency repositories
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -yqq --no-install-recommends build-essential libgtk-3-dev python3 python3-toml podman build-essential pkg-config libssl-dev
      - name: Install rust deps
        run: sudo apt-get install -yqq build-essential pkg-config libssl-dev
      - uses: actions/checkout@v3
      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $(python3 ./build-tools/rust-version-extractor/rust-version-extractor.py)
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build the wasm module
        working-directory: ./wasm-crypto
        run: wasm-pack build --target nodejs
      - name: Run the tests
        working-directory: ./wasm-crypto
        run: node js-bindings/node-entry.js
